# Generated by Django 3.2 on 2021-05-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='id',
        ),
        migrations.AlterField(
            model_name='products',
            name='urlh',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
